In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('.\材料報價總覽 - 001.csv')
target = pd.read_csv('.\材料報價總覽 - Target.csv')

In [2]:
print('original data :',data.shape)

data = pd.concat([data, target], 0)
data.reset_index(inplace=True, drop=True)
print('concat data :',data.shape)
data.tail()

original data : (170, 61)
concat data : (171, 61)


報價日期 報價廠商    專案名      數量          外盒 外盒材質 外盒印刷    外盒加工  外盒單價 外盒新刀  \
166   2019-3-25   墨帥     漢堡   500.0    70x70x60  圓筒盒   4c     NaN  50.0  NaN   
167   2019-3-25   墨帥     漢堡  1000.0    70x70x60  圓筒盒   4c     NaN  44.5  NaN   
168   2019-1-14   墨帥     漢堡   500.0  100x100x80  圓筒盒   4c     NaN  52.0  NaN   
169   2019-1-14   墨帥     漢堡  1000.0  100x100x80  圓筒盒   4c     NaN  43.0  NaN   
170  2019-12-19   墨帥  兵姬中文版   500.0  224x224x38  天地盒   4c  水消+局部光   NaN  NaN   

     ... 配件單價  配件.1  配件材質.1 配件加工.1 配件數量.1 配件單價.1  包裝單價 外箱單價   專案單價      專案總價  
166  ...  NaN   NaN     NaN    NaN    NaN    NaN  14.0  2.3  152.3   76150.0  
167  ...  NaN   NaN     NaN    NaN    NaN    NaN  12.0  2.3  121.3  121300.0  
168  ...  NaN   NaN     NaN    NaN    NaN    NaN  13.0  2.3  151.3   75650.0  
169  ...  NaN   NaN     NaN    NaN    NaN    NaN  10.0  2.3  115.8  115800.0  
170  ...  NaN   NaN     NaN    NaN    NaN    NaN   NaN  NaN    NaN       NaN  

[5 rows x 61 columns]

In [3]:
index = data.iloc[:, :4]
index.head(3)

報價日期 報價廠商   專案名      數量
0  2019-12-17   墨帥  MOTT   500.0
1  2019-12-05   墨帥  原子怪獸  1000.0
2  2019-12-05   墨帥  原子怪獸  1500.0

In [4]:
#擷取兩份卡片資料表
card = data.iloc[:, 13:21]
card2 = data.iloc[:, 21:29]
card = pd.concat([index, card], 1)
card2 = pd.concat([index, card2], 1)
card2.columns = card.columns

In [5]:
#篩選有效資料
card = card[card['卡片'].notnull()]
card2 = card2[card2['卡片'].notnull()]

#合併兩組card資料表
card = pd.concat([card, card2], 0)
card.reset_index(inplace=True, drop=True)

'''
【特別注意】
card2['卡片數量']都是整數，dtype為int64，與card合併後Object內容物type不變造成split運算錯誤。(.str只能針對str物件)
合併到card的target項目同理。
這部分必須非常細心。

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓處理↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
'''
card['卡片數量'] = card['卡片數量'].astype('str')

In [6]:
pd.DataFrame(card.isnull().sum(), columns=['Miss_Data']).T

報價日期  報價廠商  專案名  數量  卡片  卡片材質  卡片印刷  卡片加工  卡片收縮  卡片數量  卡片單價  卡片新刀
Miss_Data     0     0    0   0   0     0     0     1     0     0     2   139

In [7]:
#拋棄非目標的未加工道林紙
card = card.drop((card[card['卡片加工'].isnull()].index[0]))

In [8]:
pd.DataFrame(card.isnull().sum(), columns=['Miss_Data']).T

報價日期  報價廠商  專案名  數量  卡片  卡片材質  卡片印刷  卡片加工  卡片收縮  卡片數量  卡片單價  卡片新刀
Miss_Data     0     0    0   0   0     0     0     0     0     0     2   138

In [9]:
# card['卡片新刀'].unique()
#整理新刀欄位

label = {np.nan:0, '有':1, '特製刀膜':1, '擋板':1}
card['卡片新刀'] = card['卡片新刀'].map(label)

In [10]:
#拆解卡片尺寸

card_in = card['卡片'].str.split('\n', expand=True)
card_in.columns=['第1尺寸', '第2尺寸', '第3尺寸']
card_in = card_in.fillna('0x0')

for i, x in enumerate(card_in.columns):
    card_in['第'+str(i+1)+'尺寸面積'] = card_in[x].str.split('x', expand=True)[0].astype('float64')\
                                    * card_in[x].str.split('x', expand=True)[1].astype('float64')
card_in.head()

第1尺寸 第2尺寸 第3尺寸  第1尺寸面積  第2尺寸面積  第3尺寸面積
0  63x88  0x0  0x0  5544.0     0.0     0.0
1  63x88  0x0  0x0  5544.0     0.0     0.0
2  63x88  0x0  0x0  5544.0     0.0     0.0
3  63x88  0x0  0x0  5544.0     0.0     0.0
4  63x88  0x0  0x0  5544.0     0.0     0.0

In [11]:
#拆解卡片數量

card_inn = card['卡片數量'].str.split('\n', expand=True)
card_inn.columns=['第1數量', '第2數量', '第3數量']
card_inn = card_inn.fillna(0).astype('float64')
card_inn.head()

第1數量  第2數量  第3數量
0  40.0   0.0   0.0
1  80.0   0.0   0.0
2  80.0   0.0   0.0
3  80.0   0.0   0.0
4  80.0   0.0   0.0

In [12]:
card_inn['總使用面積'] = card_in['第1尺寸面積'] * card_inn['第1數量'] + \
                    card_in['第2尺寸面積'] * card_inn['第2數量'] + \
                    card_in['第3尺寸面積'] * card_inn['第3數量']
card_inn.head()

第1數量  第2數量  第3數量     總使用面積
0  40.0   0.0   0.0  221760.0
1  80.0   0.0   0.0  443520.0
2  80.0   0.0   0.0  443520.0
3  80.0   0.0   0.0  443520.0
4  80.0   0.0   0.0  443520.0

In [13]:
#合併拆解後資料

card = pd.concat([card, card_in], 1)
card = pd.concat([card, card_inn], 1)
del card_in, card_inn
card = card.drop(columns=['報價廠商', '卡片', '卡片數量'])
card.head()

報價日期   專案名      數量      卡片材質   卡片印刷    卡片加工 卡片收縮  卡片單價  卡片新刀   第1尺寸  \
0  2019-12-17  MOTT   500.0  350g中華寧波  4c/4c  撲克油+壓紋   收縮  58.0     0  63x88   
1  2019-12-05  原子怪獸  1000.0  310g日本銅西  4c/4c  撲克油+壓紋  2收縮  39.0     0  63x88   
2  2019-12-05  原子怪獸  1500.0  310g日本銅西  4c/4c  撲克油+壓紋  2收縮  37.0     0  63x88   
3  2019-12-05  原子怪獸  2000.0  310g日本銅西  4c/4c  撲克油+壓紋  2收縮  35.2     0  63x88   
4  2019-12-05  原子怪獸  4000.0  310g日本銅西  4c/4c  撲克油+壓紋  2收縮  29.2     0  63x88   

  第2尺寸 第3尺寸  第1尺寸面積  第2尺寸面積  第3尺寸面積  第1數量  第2數量  第3數量     總使用面積  
0  0x0  0x0  5544.0     0.0     0.0  40.0   0.0   0.0  221760.0  
1  0x0  0x0  5544.0     0.0     0.0  80.0   0.0   0.0  443520.0  
2  0x0  0x0  5544.0     0.0     0.0  80.0   0.0   0.0  443520.0  
3  0x0  0x0  5544.0     0.0     0.0  80.0   0.0   0.0  443520.0  
4  0x0  0x0  5544.0     0.0     0.0  80.0   0.0   0.0  443520.0

In [14]:
#拆解日期
import datetime
card['報價日期'] = card['報價日期'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))
card['報價年份'] = card['報價日期'].apply(lambda x: datetime.datetime.strftime(x, '%Y')).astype('int64')
card['報價月份'] = card['報價日期'].apply(lambda x: datetime.datetime.strftime(x, '%m')).astype('int64')
card['報價日'] = card['報價日期'].apply(lambda x: datetime.datetime.strftime(x, '%d')).astype('int64')

card = card.drop(columns=['報價日期'])

In [15]:
#Label encoding

label = ['專案名', '卡片材質', '卡片印刷', '卡片加工', '卡片收縮', '第1尺寸', '第2尺寸', '第3尺寸']
for x in label:
    card[x] = card[x].astype('category').cat.codes

In [16]:
card.columns

Index(['專案名', '數量', '卡片材質', '卡片印刷', '卡片加工', '卡片收縮', '卡片單價', '卡片新刀', '第1尺寸',
       '第2尺寸', '第3尺寸', '第1尺寸面積', '第2尺寸面積', '第3尺寸面積', '第1數量', '第2數量', '第3數量',
       '總使用面積', '報價年份', '報價月份', '報價日'],
      dtype='object')

In [17]:
'''
本次執行還在同年份不使用年份欄位
'''
card = card[['專案名', '數量', '卡片材質', '卡片印刷', '卡片加工', '卡片收縮', '卡片新刀', '第1尺寸',
       '第2尺寸', '第3尺寸', '第1尺寸面積', '第2尺寸面積', '第3尺寸面積', '第1數量', '第2數量', '第3數量',
       '總使用面積', '報價年份', '報價月份', '報價日', '卡片單價']]
card.head()

專案名      數量  卡片材質  卡片印刷  卡片加工  卡片收縮  卡片新刀  第1尺寸  第2尺寸  第3尺寸  ...  第2尺寸面積  \
0    5   500.0     8     0     5     5     0    13     0     0  ...     0.0   
1   19  1000.0     4     0     5     0     0    13     0     0  ...     0.0   
2   19  1500.0     4     0     5     0     0    13     0     0  ...     0.0   
3   19  2000.0     4     0     5     0     0    13     0     0  ...     0.0   
4   19  4000.0     4     0     5     0     0    13     0     0  ...     0.0   

   第3尺寸面積  第1數量  第2數量  第3數量     總使用面積  報價年份  報價月份  報價日  卡片單價  
0     0.0  40.0   0.0   0.0  221760.0  2019    12   17  58.0  
1     0.0  80.0   0.0   0.0  443520.0  2019    12    5  39.0  
2     0.0  80.0   0.0   0.0  443520.0  2019    12    5  37.0  
3     0.0  80.0   0.0   0.0  443520.0  2019    12    5  35.2  
4     0.0  80.0   0.0   0.0  443520.0  2019    12    5  29.2  

[5 rows x 21 columns]

# 預測

In [18]:
'''
改動 預測目標
'''
target = card[card['卡片單價'].isnull()]
card = card.dropna()

In [19]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import cross_val_score, GridSearchCV

### RandomForestRegression

In [20]:
rfModel = RandomForestRegressor()
rfModel.fit(card.iloc[:, : -1], card.iloc[:, -1])
cross_val_score(rfModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

0.6806184631383281

In [21]:
submit_rf = rfModel.predict(target.iloc[:, :-1])
submit_rf

array([93.066, 52.2  ])

### GradientBoostingRegression

In [22]:
gbModel = GradientBoostingRegressor()
gbModel.fit(card.iloc[:, :-1], card.iloc[:, -1])
cross_val_score(gbModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

0.7283661875070909

In [23]:
submit_gb = gbModel.predict(target.iloc[:, :-1])
submit_gb

array([110.01250884,  49.92310242])

### XGB

In [24]:
xgb = XGBRegressor()
xgb.fit(card.iloc[:, :-1], card.iloc[:, -1])
cross_val_score(xgb, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:49:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.6982010053264572

In [25]:
submit_xgb = xgb.predict(target.iloc[:, :-1])
submit_xgb

array([107.64093 ,  34.647675], dtype=float32)

### LightGBM

In [26]:
lgbm = LGBMRegressor(objective='regression')
lgbm.fit(card.iloc[:, :-1], card.iloc[:, -1])
cross_val_score(lgbm, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

-1.8381398032309317

In [27]:
submit_lgbm = lgbm.predict(target.iloc[:, :-1])
submit_lgbm

array([97.62648978, 82.45246367])

# Submit

In [28]:
submit = []
submit.append(submit_rf)
submit.append(submit_gb)
submit.append(submit_xgb)
submit.append(submit_lgbm)
pd.DataFrame(submit, index=pd.Index(['rfModel', 'gbModel', 'xgbModel', 'lgbmModel']), columns=['卡片1預測', '卡片2預測'])

卡片1預測      卡片2預測
rfModel     93.066000  52.200000
gbModel    110.012509  49.923102
xgbModel   107.640930  34.647675
lgbmModel   97.626490  82.452464

----
# Hyperparameter

In [29]:
param_grid = {'learning_rate':[0.1, 0.3, 0.5],
              'n_estimators':[100, 200, 300],
              'subsample':[1.0, 0.5, 0.3, 0.1],
              'min_samples_split':[2, 5, 10],
              'min_samples_leaf':[1, 2, 4],
              'max_depth':[3, 6, 8],
              'tol':[0.01, 0.05, 0.1]}
gridsearch = GridSearchCV(gbModel, param_grid, n_jobs=-1, verbose=1)
grid_result = gridsearch.fit(card.iloc[:, :-1], card.iloc[:, -1])

print('Best Accuracy : {}\nUsing {}'.format(grid_result.best_score_, grid_result.best_params_))

Fitting 3 folds for each of 2916 candidates, totalling 8748 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.9s
[Parallel(n_jobs=-1)]: Done 322 tasks      | elapsed:    6.0s
[Parallel(n_jobs=-1)]: Done 822 tasks      | elapsed:   10.8s
[Parallel(n_jobs=-1)]: Done 1522 tasks      | elapsed:   18.7s
[Parallel(n_jobs=-1)]: Done 2422 tasks      | elapsed:   29.1s
[Parallel(n_jobs=-1)]: Done 3522 tasks      | elapsed:   41.0s
[Parallel(n_jobs=-1)]: Done 4822 tasks      | elapsed:   55.3s
[Parallel(n_jobs=-1)]: Done 6322 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 8022 tasks      | elapsed:  1.5min


Best Accuracy : 0.8614367681476202
Using {'learning_rate': 0.3, 'max_depth': 6, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100, 'subsample': 1.0, 'tol': 0.1}


[Parallel(n_jobs=-1)]: Done 8748 out of 8748 | elapsed:  1.7min finished
C:\Users\camer\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [30]:
hyper_gbModel = GradientBoostingRegressor(learning_rate=0.3,
                                          max_depth=6,
                                          min_samples_leaf=1,
                                          min_samples_split=5,
                                          n_estimators=100,
                                          subsample=1.0, tol=0.05)
hyper_gbModel.fit(card.iloc[:, :-1], card.iloc[:, -1])
cross_val_score(hyper_gbModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

0.686525215382599

In [31]:
submit_hyper_gbModel = hyper_gbModel.predict(target.iloc[:, :-1])
submit_hyper_gbModel

array([86.54834865, 75.11298277])

In [32]:
param_grid = {'n_estimators':[100, 200, 300],
              'min_child_weight':[1, 5, 10],
             'gamma':[0.5, 1, 1.5, 2, 5],
             'subsample':[0.6, 0.8, 1.0],
             'max_depth':[3, 4, 5]}
gridsearch = GridSearchCV(xgb, param_grid, cv=5, n_jobs=-1, verbose=1)
grid_result = gridsearch.fit(card.iloc[:, :-1], card.iloc[:, -1])
print('Best Accuracy : {}\nUsing {}'.format(grid_result.best_score_, grid_result.best_params_) )

Fitting 5 folds for each of 405 candidates, totalling 2025 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 688 tasks      | elapsed:    8.8s
[Parallel(n_jobs=-1)]: Done 1688 tasks      | elapsed:   22.2s


[00:52:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Best Accuracy : 0.7473846193966023
Using {'gamma': 1.5, 'max_depth': 3, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.6}


[Parallel(n_jobs=-1)]: Done 2025 out of 2025 | elapsed:   26.9s finished
C:\Users\camer\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [33]:
hyper_xgb = XGBRegressor(gamma=1.5,
                         max_depth=3,
                         min_child_weight=1,
                         n_estimators=300,
                         subsample=0.6)
hyper_xgb.fit(card.iloc[:, :-1], card.iloc[:, -1])
cross_val_score(hyper_xgb, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()

[00:52:51] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:52:51] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:52:51] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:52:51] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:52:51] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[00:52:52] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.7465694787582813

In [34]:
submit_hyper_xgb = hyper_xgb.predict(target.iloc[:, :-1])
submit_hyper_xgb

array([113.597824,  44.827076], dtype=float32)

In [35]:
submit.append(submit_hyper_gbModel)
submit.append(submit_hyper_xgb)
pd.DataFrame(submit, index=pd.Index(['rfModel', 'gbModel', 'xgbModel', 'lgbmModel', 'hyper_gbModel', 'hyper_xgbModel']),
             columns=['卡片1預測', '卡片2預測'])

卡片1預測      卡片2預測
rfModel          93.066000  52.200000
gbModel         110.012509  49.923102
xgbModel        107.640930  34.647675
lgbmModel        97.626490  82.452464
hyper_gbModel    86.548349  75.112983
hyper_xgbModel  113.597824  44.827076

In [44]:
#追加信心水準
level = [cross_val_score(rfModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean(),
         cross_val_score(gbModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean(),
         cross_val_score(xgb, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean(),
         cross_val_score(lgbm, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean(),
         cross_val_score(hyper_gbModel, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean(),
         cross_val_score(hyper_xgb, card.iloc[:, :-1], card.iloc[:, -1], cv=5).mean()]

df_level = pd.DataFrame(level, columns=['預測信心'])
df = pd.DataFrame(submit, columns=['卡片1預測', '卡片2預測'])
df = pd.concat([df, df_level], 1)
df.index=pd.Index(['rfModel', 'gbModel', 'xgbModel', 'lgbmModel', 'hyper_gbModel', 'hyper_xgbModel'])

[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[01:00:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is n

In [45]:
df

卡片1預測      卡片2預測      預測信心
rfModel          93.066000  52.200000  0.709036
gbModel         110.012509  49.923102  0.731059
xgbModel        107.640930  34.647675  0.698201
lgbmModel        97.626490  82.452464 -1.838140
hyper_gbModel    86.548349  75.112983  0.666446
hyper_xgbModel  113.597824  44.827076  0.746569